version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Is-Uppercase"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1faa6ofiogdt9"
s3_prefix = "Is-Uppercase"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
